### ISSUE TITLE
[bug][1.12.2]ocean virus and red virus id conflict

### ISSUE THREAD

**Issue by tonimark** [ThunderModder/bionisation3#15]
so I attempted here and some time to test ocean virus until I found out about an id conflict between red virus and ocean virus:
![2019-04-21_14 58 07](https://user-images.githubusercontent.com/17166550/56469734-299aa600-6446-11e9-9a14-4472765ca76d.png)
![2019-04-21_14 58 06](https://user-images.githubusercontent.com/17166550/56469737-2d2e2d00-6446-11e9-89d5-5a701d27c8e0.png)

**Comment by tonimark** [comment]
hello, anyone, this is a high priority issue, it is so annoying that I tried to fix myself ??! :(

**Comment by tonimark** [comment]
by the way, this also causes issues because you can't get vampire-ocean symbiosis because it's impossible to get ocean virus by this major bug (i saw it in comments (of curseforge saying about a bug, but he didn't post it on issues so I do it for him).

**Comment by DoctorFTB** [comment]
Omg. Pls, if u not get help less one day - IT NORMALLY. You not need SPAMIMG. Thanks.

Try 1.0.8 update.

**Comment by tonimark** [comment]
sorry but this bug seems very annoying @DoctorFTB 
by the way, I see that you can't also teleport with ender virus, investigate it

**Comment by tonimark** [comment]
ok I will try the 1.0.8 update

**Comment by tonimark** [comment]
@DoctorFTB  hmmm seems like something wrong, Minecraft crashes at initializing but it doesn't count it as a crash, it thinks it crashed without reason, I will create an issue and post the log for investigation

**Comment by tonimark** [comment]
forget it I realize that is an issue with forge, I use the latest due to incompatibility with some mods

**Comment by tonimark** [comment]
it seems like an issue with another mod sorry anyway, I will investigate my mods

**Comment by tonimark** [comment]
minecraft and mod seems to work fine thanks
