### ISSUE TITLE
[1.12.2] Player Caps proper sync fix

### ISSUE THREAD

**Issue by ZigTheHedge** [ThunderModder/bionisation3#18]
When one's teleporting between dimensions, sometimes blood HUD gets out of sync with server. Well, I ran into very same issue with my mod and finally found out where the problem is :)
You should use thread-safe message handler like so (same for SyncAllCaps handler):

    public static class Handler implements IMessageHandler<SyncBloodCapMessage, IMessage> {
        @Override
        public IMessage onMessage(SyncBloodCapMessage message, MessageContext ctx) {
            Minecraft.getMinecraft().addScheduledTask(() -> {
                        Minecraft mc = Minecraft.getMinecraft();
                        IBioPlayer cap = mc.player.getCapability(BioPlayerProvider.BIO_PLAYER_CAPABILITY, null);
                        if(cap != null)
                            cap.setBloodLevel(message.value);
                    });
            return null;
    }

**Comment by DoctorFTB** [comment]
Try 1.0.9 version.

(P.S. Удачного лп)
